Repository kiegroup/kogito-pipelines, pull requests merged in 2023-02, with the labels that each got.

#830 Build-chain: Allow to setup default quarkus version in env
  .ci/jenkins/Jenkinsfile.buildchain
  dsl/config/branch.yaml
Labels: backport-1.34.x, backport-seed-kogito-1.34.x, backport-seed-optaplanner-8.34.x, backport-seed-drools-8.34.x

#838 Correct PR target branch
  dsl/seed/src/main/groovy/org/kie/jenkins/jobdsl/KogitoJobTemplate.groovy
Labels: backport-1.34.x

#846 DSL: Correct update Jenkins dependencies
  .ci/jenkins/Jenkinsfile.tools.update-jenkins-dependencies
Labels: backport-seed-kogito-1.33.x, backport-seed-optaplanner-8.33.x, backport-seed-kogito-1.34.x, backport-seed-optaplanner-8.34.x, backport-seed-drools-8.34.x

#853 Quarkus platform job: Allow to change branch
  .ci/jenkins/Jenkinsfile.update-quarkus-platform
  dsl/seed/src/main/groovy/org/kie/jenkins/jobdsl/KogitoJobUtils.groovy
Labels: backport-seed-kogito-1.34.x, backport-seed-optaplanner-8.34.x, backport-seed-drools-8.34.x

#858 Update Jenkinsfile.tools.update-jenkins-dependencies
  .ci/jenkins/Jenkinsfile.tools.update-jenkins-dependencies
Labels: backport-seed-kogito-1.33.x

#860 DSL Config: Update Git credentials
  dsl/config/branch.yaml
Labels: backport-1.33.x, backport-1.13.x, backport-1.13.x-blue, backport-1.34.x

#870 DSL branch Config: Revert quarkus credentials
  dsl/config/branch.yaml
Labels: backport-1.33.x, backport-1.34.x

#876 KOGITO-8706 Correct toggle triggers
  .ci/jenkins/Jenkinsfile.toggle-triggers
  .ci/jenkins/dsl/jobs.groovy
  dsl/seed/jenkinsfiles/Jenkinsfile.tools.toggle-triggers
  dsl/seed/jobs/seed_job_branch.groovy
Labels: backport-1.34.x, backport-seed-kogito-1.34.x, backport-seed-optaplanner-8.34.x, backport-seed-drools-8.34.x

#883 Revert "Revert "[1.13.x] Bump Quarkus version to 2.13.4.Final""
  .ci/actions/maven/action.yml
  .ci/jenkins/Jenkinsfile.buildchain
  .ci/jenkins/Jenkinsfile.prod.nightly
  .ci/jenkins/Jenkinsfile.tools.update-dependency-version
  kogito-operator-jenkins-node/image.yaml
Labels: backport-1.13.x-blue

#887 [1.13.x-blue] Correct Build Chain pipeline on Jenkins
  .ci/jenkins/Jenkinsfile.buildchain
Labels: cherry pick :cherries:
